=== VicNew/newtoms-landingpage-system-api/src/main/api/schemas/CreateNewLeadResponseSchema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://newtoms.com/root.json",
  "type": "object",
  "title": "Create New Lead Response Schema",
  "required": [
    "id",
    "firstName",
    "lastName",
    "company",
    "title",
    "email",
    "status",
    "links"
  ],
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "integer",
      "title": "The Id Schema",
      "default": 0,
      "examples": [
        1
      ]
    },
    "firstName": {
      "$id": "#/properties/firstName",
      "type": "string",
      "title": "The Firstname Schema",
      "default": "",
      "examples": [
        "Victor"
      ],
      "pattern": "^(.*)$"
    },
    "lastName": {
      "$id": "#/properties/lastName",
      "type": "string",
      "title": "The Lastname Schema",
      "default": "",
      "examples": [
        "Luna"
      ],
      "pattern": "^(.*)$"
    },
    "company": {
      "$id": "#/properties/company",
      "type": "string",
      "title": "The Company Schema",
      "default": "",
      "examples": [
        "Newtoms"
      ],
      "pattern": "^(.*)$"
    },
    "title": {
      "$id": "#/properties/title",
      "type": "string",
      "title": "The Title Schema",
      "default": "",
      "examples": [
        "Developer"
      ],
      "pattern": "^(.*)$"
    },
    "email": {
      "$id": "#/properties/email",
      "type": "string",
      "title": "The Email Schema",
      "default": "",
      "examples": [
        "victor.luna@newtoms.com"
      ],
      "pattern": "^(.*)$"
    },
    "status": {
      "$id": "#/properties/status",
      "type": "string",
      "title": "The Status Schema",
      "default": "",
      "examples": [
        "Created"
      ],
      "pattern": "^(.*)$"
    },
    "links": {
      "$id": "#/properties/links",
      "type": "array",
      "title": "The Links Schema",
      "items": {
        "$id": "#/properties/links/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "rel",
          "uri",
          "method"
        ],
        "properties": {
          "rel": {
            "$id": "#/properties/links/items/properties/rel",
            "type": "string",
            "title": "The Rel Schema",
            "default": "",
            "examples": [
              "/linkrels/lead/info"
            ],
            "pattern": "^(.*)$"
          },
          "uri": {
            "$id": "#/properties/links/items/properties/uri",
            "type": "string",
            "title": "The Uri Schema",
            "default": "",
            "examples": [
              "/landingpage/lead/1234"
            ],
            "pattern": "^(.*)$"
          },
          "method": {
            "$id": "#/properties/links/items/properties/method",
            "type": "string",
            "title": "The Method Schema",
            "default": "",
            "examples": [
              "GET"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    }
  }
}

=== VicNew/newtoms-landingpage-system-api/src/main/api/examples/CreateNewLeadResponse.json
{
   "id":1,
   "firstName":"Victor",
   "lastName":"Luna",
   "company":"Newtoms",
   "title":"Developer",
   "email":"victor.luna@newtoms.com",
   "status":"Created",
   "links":[
      {
         "rel":"/linkrels/lead/info",
         "uri":"/landingpage/lead/1234",
         "method":"GET"
      },
      {
         "rel":"/linkrels/lead/updateInfo",
         "uri":"/landingpage/lead/1234",
         "method":"PUT"
      },
      {
         "rel":"/linkrels/lead/delete",
         "uri":"/landingpage/lead/1234",
         "method":"DELETE"
      }
   ]
}
